### ISSUE TITLE
Unexpected unknown type selector "disabled" in 18201131_bootsrapvue.scss

### ISSUE THREAD

**Issue by McLaynV** [cortezaproject/corteza#2022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2024.9.x branch

### Current Behavior

The `server/assets/src/scss/main/18201131_bootsrapvue.scss` file contains: 
```scss
  a,
  .btn {
    &.b-avatar:hover:not(.disabled):not(disabled) {
      z-index: 1;
    }
  }
```
and `disabled` is not a valid selector in `:not(disabled)`. 

### Expected Behavior

I believe it should be `:not([disabled])` which means "element does not have the `disabled` attribute".
```scss
  a,
  .btn {
    &.b-avatar:hover:not(.disabled):not([disabled]) {
      z-index: 1;
    }
  }
```

### Anything else?

Implemented in #2023 PR
